CREATE OR ALTER FUNCTION udf_ProjectlenInWeeks(@Start DATETIME, @END DATETIME)
RETURNS INT
AS BEGIN
	DECLARE @Result INT
	IF (@End IS NULL)
		SET @End = GETDATE()
	SET @Result = DATEDIFF(WEEK, @Start, @End)
	RETURN @Result
END
--SCALAR FUNCTION